### ISSUE TITLE
Формат данных ответа

### ISSUE THREAD

**Issue by mirecl** [povstenid/RRB#1]
Ответ должен быть в формате `json`, а не в `str`.
На данные момент:
```text
'{\n "31.01.2022": 15068.75,\n "28.02.2022": 15137.82,\n "31.03.2022": 15207.2,\n "30.04.2022": 15276.9,\n "31.05.2022": 15346.92,\n "30.06.2022": 15417.26,\n "31.07.2022": 15487.92,\n "31.08.2022": 15558.9\n}'
```
Ожидалось:
```json
{
   '31.01.2022': 15068.75,
   '28.02.2022': 15137.82,
   '31.03.2022': 15207.2,
   '30.04.2022': 15276.9,
   '31.05.2022': 15346.92,
   '30.06.2022': 15417.26,
   '31.07.2022': 15487.92,
   '31.08.2022': 15558.9
}
```

**Comment by povstenid** [comment]
![image](https://user-images.githubusercontent.com/93582400/140901742-90485192-7987-4e84-983e-4328fe8f12c2.png)
В тестовом задании указаны одинарные кавычки.  Согласно стандарту JSON они равны, но тем не менее.

Баг исправлен, сейчас возвращается JSON

**Comment by mirecl** [comment]
Данное представление JSON - стандартное для браузеров и ЯП...
