### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by mirecl** [povstenid/RRB#3]
Привести код к `PEP8` (Style Guide for Python Code).

**Comment by povstenid** [comment]
PEP 8 не рекомендует использовать "except" без указания типа ошибки, но для тестового примера полагаю это избыточным.
Остальные будет приведено к PEP 8.

**Comment by mirecl** [comment]
Предлагаю по максимум устранить все.

**Comment by povstenid** [comment]
Устранено все, кроме "broad exception"
